# Generated by Django 3.1.7 on 2021-03-14 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210314_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchase',
            name='time_of_return',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 19, 6, 16, 632388)),
        ),
    ]
