# Generated by Django 3.1.7 on 2021-03-14 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210314_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchase',
            name='time_of_return',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 20, 21, 16, 397283)),
        ),
        migrations.AlterField(
            model_name='snus',
            name='picture',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
