# Generated by Django 3.1.7 on 2021-03-14 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210314_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchase',
            name='time_of_return',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 20, 24, 36, 466764)),
        ),
        migrations.AlterField(
            model_name='snus',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
