# Generated by Django 3.1.7 on 2021-03-16 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210314_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 15, 1, 5, 917082)),
        ),
        migrations.AlterField(
            model_name='returnpurchase',
            name='time_of_return',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 15, 1, 5, 920071)),
        ),
    ]
