# Generated by Django 3.1.7 on 2021-03-18 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210318_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchase',
            name='time_of_return',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 0, 9, 31, 373324)),
        ),
    ]
