# Generated by Django 3.1.7 on 2021-03-18 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210319_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchase',
            name='time_of_return',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 0, 13, 48, 308488)),
        ),
    ]
