# Generated by Django 3.1.7 on 2021-03-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210319_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchase',
            name='time_of_return',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
