# Generated by Django 3.1.7 on 2021-03-23 21:14

from django.db import migrations


def some_forward_action(apps, schema_editor):
    Snus = apps.get_model('store', 'Snus') # Приложение и модель
    Snus.objects.create(title='Tropic', description='Added from migrations', price=5, quantity=4 )
    Snus.objects.create(title='New', description='Added from migrations too', price=7, quantity=5)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210319_0014'),
    ]

    operations = [
        migrations.RunPython(some_forward_action, lambda x, y: None)
    ]
