# Generated by Django 3.1.7 on 2021-03-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210323_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snus',
            name='picture',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
    ]
