# Generated by Django 3.1.7 on 2021-03-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210326_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snus',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media'),
        ),
    ]
