# Generated by Django 3.1.7 on 2021-03-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210326_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[(1, 'Man'), (2, 'Woman')], max_length=100)),
                ('age', models.IntegerField()),
                ('english_lvl', models.CharField(choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], max_length=100)),
            ],
        ),
    ]
